/**
 * Customer Validation Schema
 * Generated by Express.js CRUD Generator
 */

import { z } from 'zod';

export const customerSchema = z.object({
  id: z.string().optional(),
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  email: z.string().email().optional(),
  phone: z.string().optional(),
  createdAt: z.string().datetime().optional(),
});
