/**
 * Common Validation Schemas
 * Generated by Express.js CRUD Generator
 */

import { z } from 'zod';

export const paginationSchema = z.object({
  page: z.coerce.number().int().positive().default(1),
  limit: z.coerce.number().int().positive().default(10),
});

export const idParamsSchema = z.object({
  id: z.string(),
});
