/**
 * Routes Index
 * Generated by Express.js CRUD Generator
 */

import { Express } from 'express';
import { articleRoutes } from './article/articleRoutes';
import { customerRoutes } from './customer/customerRoutes';
import { orderRoutes } from './order/orderRoutes';
import { orderItemRoutes } from './orderItem/orderItemRoutes';
import { unitRoutes } from './unit/unitRoutes';

export function registerRoutes(app: Express): void {
  app.use('/articles', articleRoutes);
  app.use('/customers', customerRoutes);
  app.use('/orders', orderRoutes);
  app.use('/orderItems', orderItemRoutes);
  app.use('/units', unitRoutes);
}
