/**
 * Unit Validation Schema
 * Generated by Express.js CRUD Generator
 */

import { z } from 'zod';

export const unitSchema = z.object({
  id: z.string().optional(),
  unitNumber: z.string().optional(),
  description: z.string().optional(),
});
