/**
 * OrderItem Validation Schema
 * Generated by Express.js CRUD Generator
 */

import { z } from 'zod';

export const orderItemSchema = z.object({
  id: z.string().optional(),
  orderId: z.string(),
  articleId: z.union([z.string(), z.null()]).optional(),
  name: z.string().optional(),
  price: z.union([z.number(), z.null()]).optional(),
  unitId: z.union([z.string(), z.null()]).optional(),
  quantity: z.number().optional(),
  lineTotal: z.number().optional(),
});
