/**
 * TypeScript Types
 * Generated by Express.js CRUD Generator
 */

export interface Article {
  id?: string;
  name: string;
  description: string;
  price: number;
  unitId: string | null;
  unit?: Unit;
  sku: string;
  inStock: boolean;
}

export interface Customer {
  id?: string;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  createdAt?: string;
}

export interface Order {
  id?: string;
  customerId: string;
  customer?: Customer;
  orderDate: string;
  status: string;
  totalAmount?: number;
  shippingAddress: string;
}

export interface OrderItem {
  id?: string;
  orderId: string;
  order?: Order;
  articleId: string | null;
  article?: Article;
  name: string;
  price: number | null;
  unitId: string | null;
  unit?: Unit;
  quantity: number;
  lineTotal?: number;
}

export interface Unit {
  id?: string;
  unitNumber: string;
  description: string;
}
