/**
 * Article Validation Schema
 * Generated by Express.js CRUD Generator
 */

import { z } from 'zod';

export const articleSchema = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  description: z.string().optional(),
  price: z.number().optional(),
  unitId: z.union([z.string(), z.null()]).optional(),
  sku: z.string().optional(),
  inStock: z.boolean().optional(),
});
