/**
 * Articles Router
 * Generated by Express.js CRUD Generator
 */

import { Router, Request, Response } from 'express';
import { Article } from '../types';

const router = Router();

// In-memory data store with example data
let articles: Article[] = [
  {
    "id": "art-001",
    "name": "Wireless Mouse",
    "description": "Ergonomic wireless mouse with USB receiver",
    "price": 29.99,
    "unitId": "unit-001",
    "unit": {
      "id": "unit-001",
      "unitNumber": "pcs",
      "description": "Pieces"
    },
    "sku": "MOUSE-WL-001",
    "inStock": true
  },
  {
    "id": "art-002",
    "name": "USB-C Cable",
    "description": "1m USB-C to USB-C charging cable",
    "price": 12.99,
    "unitId": "unit-001",
    "unit": {
      "id": "unit-001",
      "unitNumber": "pcs",
      "description": "Pieces"
    },
    "sku": "CABLE-USBC-1M",
    "inStock": true
  },
  {
    "id": "art-003",
    "name": "Mechanical Keyboard",
    "description": "RGB mechanical keyboard with blue switches",
    "price": 89.99,
    "unitId": "unit-001",
    "unit": {
      "id": "unit-001",
      "unitNumber": "pcs",
      "description": "Pieces"
    },
    "sku": "KB-MECH-RGB",
    "inStock": false
  }
];

// Helper to generate ID
const generateId = (): string => `article-${String(articles.length + 1).padStart(3, '0')}`;

/**
 * GET /articles
 * List all articles with pagination
 */
router.get('/', (req: Request, res: Response) => {
  const page = parseInt(req.query.page as string) || 1;
  const limit = parseInt(req.query.limit as string) || 10;
  const offset = (page - 1) * limit;

  const paginatedData = articles.slice(offset, offset + limit);

  res.json({
    data: paginatedData,
    total: articles.length,
    page,
    limit
  });
});

/**
 * POST /articles
 * Create a new article
 */
router.post('/', (req: Request, res: Response) => {
  const newArticle: Article = {
    id: generateId(),
    ...req.body,
    
  };

  articles.push(newArticle);
  res.status(201).json(newArticle);
});

/**
 * GET /articles/:id
 * Get a article by ID
 */
router.get('/:id', (req: Request, res: Response) => {
  const article = articles.find(item => item.id === req.params.id);

  if (!article) {
    return res.status(404).json({
      error: 'Not Found',
      message: `Article with id '${req.params.id}' not found`
    });
  }

  res.json(article);
});

/**
 * PUT /articles/:id
 * Update a article
 */
router.put('/:id', (req: Request, res: Response) => {
  const index = articles.findIndex(item => item.id === req.params.id);

  if (index === -1) {
    return res.status(404).json({
      error: 'Not Found',
      message: `Article with id '${req.params.id}' not found`
    });
  }

  const updatedArticle: Article = {
    ...articles[index],
    ...req.body,
    id: req.params.id // Ensure ID cannot be changed
  };

  articles[index] = updatedArticle;
  res.json(updatedArticle);
});

/**
 * DELETE /articles/:id
 * Delete a article
 */
router.delete('/:id', (req: Request, res: Response) => {
  const index = articles.findIndex(item => item.id === req.params.id);

  if (index === -1) {
    return res.status(404).json({
      error: 'Not Found',
      message: `Article with id '${req.params.id}' not found`
    });
  }

  articles.splice(index, 1);
  res.status(204).send();
});

export { router as articlesRouter };
