/**
 * Customers Router
 * Generated by Express.js CRUD Generator
 */

import { Router, Request, Response } from 'express';
import { Customer } from '../types';

const router = Router();

// In-memory data store with example data
let customers: Customer[] = [
  {
    "id": "cust-001",
    "firstName": "John",
    "lastName": "Doe",
    "email": "john.doe@example.com",
    "phone": "+1-555-123-4567",
    "createdAt": "2024-01-15T10:30:00Z"
  },
  {
    "id": "cust-002",
    "firstName": "Jane",
    "lastName": "Smith",
    "email": "jane.smith@example.com",
    "phone": "+1-555-987-6543",
    "createdAt": "2024-02-20T14:45:00Z"
  },
  {
    "id": "cust-003",
    "firstName": "Bob",
    "lastName": "Johnson",
    "email": "bob.johnson@example.com",
    "phone": "+1-555-456-7890",
    "createdAt": "2024-03-10T09:15:00Z"
  }
];

// Helper to generate ID
const generateId = (): string => `customer-${String(customers.length + 1).padStart(3, '0')}`;

/**
 * GET /customers
 * List all customers with pagination
 */
router.get('/', (req: Request, res: Response) => {
  const page = parseInt(req.query.page as string) || 1;
  const limit = parseInt(req.query.limit as string) || 10;
  const offset = (page - 1) * limit;

  const paginatedData = customers.slice(offset, offset + limit);

  res.json({
    data: paginatedData,
    total: customers.length,
    page,
    limit
  });
});

/**
 * POST /customers
 * Create a new customer
 */
router.post('/', (req: Request, res: Response) => {
  const newCustomer: Customer = {
    id: generateId(),
    ...req.body,
    createdAt: new Date().toISOString(),
  };

  customers.push(newCustomer);
  res.status(201).json(newCustomer);
});

/**
 * GET /customers/:id
 * Get a customer by ID
 */
router.get('/:id', (req: Request, res: Response) => {
  const customer = customers.find(item => item.id === req.params.id);

  if (!customer) {
    return res.status(404).json({
      error: 'Not Found',
      message: `Customer with id '${req.params.id}' not found`
    });
  }

  res.json(customer);
});

/**
 * PUT /customers/:id
 * Update a customer
 */
router.put('/:id', (req: Request, res: Response) => {
  const index = customers.findIndex(item => item.id === req.params.id);

  if (index === -1) {
    return res.status(404).json({
      error: 'Not Found',
      message: `Customer with id '${req.params.id}' not found`
    });
  }

  const updatedCustomer: Customer = {
    ...customers[index],
    ...req.body,
    id: req.params.id // Ensure ID cannot be changed
  };

  customers[index] = updatedCustomer;
  res.json(updatedCustomer);
});

/**
 * DELETE /customers/:id
 * Delete a customer
 */
router.delete('/:id', (req: Request, res: Response) => {
  const index = customers.findIndex(item => item.id === req.params.id);

  if (index === -1) {
    return res.status(404).json({
      error: 'Not Found',
      message: `Customer with id '${req.params.id}' not found`
    });
  }

  customers.splice(index, 1);
  res.status(204).send();
});

export { router as customersRouter };
