/**
 * Routes Index
 * Generated by Express.js CRUD Generator
 */

import type { Express } from 'express';
import { articleRoutes } from './article/articleRoutes.ts';
import { customerRoutes } from './customer/customerRoutes.ts';
import { orderRoutes } from './order/orderRoutes.ts';
import { orderItemRoutes } from './orderItem/orderItemRoutes.ts';
import { unitRoutes } from './unit/unitRoutes.ts';

export function registerRoutes(app: Express): void {
  app.use('/articles', articleRoutes);
  app.use('/customers', customerRoutes);
  app.use('/orders', orderRoutes);
  app.use('/orderItems', orderItemRoutes);
  app.use('/units', unitRoutes);
}
