/**
 * Routes Index
 * Generated by Express.js CRUD Generator
 */

import { Express } from 'express';
import { articlesRouter } from './articles';
import { customersRouter } from './customers';
import { ordersRouter } from './orders';
import { orderItemsRouter } from './orderItems';
import { unitsRouter } from './units';

export function registerRoutes(app: Express): void {
  app.use('/articles', articlesRouter);
  app.use('/customers', customersRouter);
  app.use('/orders', ordersRouter);
  app.use('/orderItems', orderItemsRouter);
  app.use('/units', unitsRouter);
}
