/**
 * OrderItems Router
 * Generated by Express.js CRUD Generator
 */

import { Router, Request, Response } from 'express';
import { OrderItem } from '../types';

const router = Router();

// In-memory data store with example data
let orderItems: OrderItem[] = [
  {
    "id": "item-001",
    "orderId": "ord-001",
    "articleId": "art-001",
    "article": {
      "id": "art-001",
      "name": "Wireless Mouse",
      "description": "Ergonomic wireless mouse with USB receiver",
      "price": 29.99,
      "unitId": "unit-001",
      "sku": "MOUSE-WL-001",
      "inStock": true
    },
    "name": "Wireless Mouse",
    "price": 29.99,
    "unitId": "unit-001",
    "unit": {
      "id": "unit-001",
      "unitNumber": "pcs",
      "description": "Pieces"
    },
    "quantity": 2,
    "lineTotal": 59.98
  },
  {
    "id": "item-002",
    "orderId": "ord-001",
    "articleId": "art-003",
    "article": {
      "id": "art-003",
      "name": "Mechanical Keyboard",
      "description": "RGB mechanical keyboard with blue switches",
      "price": 89.99,
      "unitId": "unit-001",
      "sku": "KB-MECH-RGB",
      "inStock": false
    },
    "name": "Mechanical Keyboard",
    "price": 89.99,
    "unitId": "unit-001",
    "unit": {
      "id": "unit-001",
      "unitNumber": "pcs",
      "description": "Pieces"
    },
    "quantity": 1,
    "lineTotal": 89.99
  },
  {
    "id": "item-003",
    "orderId": "ord-003",
    "articleId": "art-002",
    "article": {
      "id": "art-002",
      "name": "USB-C Cable",
      "description": "1m USB-C to USB-C charging cable",
      "price": 12.99,
      "unitId": "unit-001",
      "sku": "CABLE-USBC-1M",
      "inStock": true
    },
    "name": "USB-C Cable",
    "price": 12.99,
    "unitId": "unit-001",
    "unit": {
      "id": "unit-001",
      "unitNumber": "pcs",
      "description": "Pieces"
    },
    "quantity": 2,
    "lineTotal": 25.98
  }
];

// Helper to generate ID
const generateId = (): string => `orderitem-${String(orderItems.length + 1).padStart(3, '0')}`;

/**
 * GET /orderItems
 * List all orderItems with pagination
 */
router.get('/', (req: Request, res: Response) => {
  const page = parseInt(req.query.page as string) || 1;
  const limit = parseInt(req.query.limit as string) || 10;
  const offset = (page - 1) * limit;

  const paginatedData = orderItems.slice(offset, offset + limit);

  res.json({
    data: paginatedData,
    total: orderItems.length,
    page,
    limit
  });
});

/**
 * POST /orderItems
 * Create a new orderItem
 */
router.post('/', (req: Request, res: Response) => {
  const newOrderItem: OrderItem = {
    id: generateId(),
    ...req.body,
    
  };

  orderItems.push(newOrderItem);
  res.status(201).json(newOrderItem);
});

/**
 * GET /orderItems/:id
 * Get a orderItem by ID
 */
router.get('/:id', (req: Request, res: Response) => {
  const orderItem = orderItems.find(item => item.id === req.params.id);

  if (!orderItem) {
    return res.status(404).json({
      error: 'Not Found',
      message: `OrderItem with id '${req.params.id}' not found`
    });
  }

  res.json(orderItem);
});

/**
 * PUT /orderItems/:id
 * Update a orderItem
 */
router.put('/:id', (req: Request, res: Response) => {
  const index = orderItems.findIndex(item => item.id === req.params.id);

  if (index === -1) {
    return res.status(404).json({
      error: 'Not Found',
      message: `OrderItem with id '${req.params.id}' not found`
    });
  }

  const updatedOrderItem: OrderItem = {
    ...orderItems[index],
    ...req.body,
    id: req.params.id // Ensure ID cannot be changed
  };

  orderItems[index] = updatedOrderItem;
  res.json(updatedOrderItem);
});

/**
 * DELETE /orderItems/:id
 * Delete a orderItem
 */
router.delete('/:id', (req: Request, res: Response) => {
  const index = orderItems.findIndex(item => item.id === req.params.id);

  if (index === -1) {
    return res.status(404).json({
      error: 'Not Found',
      message: `OrderItem with id '${req.params.id}' not found`
    });
  }

  orderItems.splice(index, 1);
  res.status(204).send();
});

export { router as orderItemsRouter };
