/**
 * Orders Router
 * Generated by Express.js CRUD Generator
 */

import { Router, Request, Response } from 'express';
import { Order } from '../types';

const router = Router();

// In-memory data store with example data
let orders: Order[] = [
  {
    "id": "ord-001",
    "customerId": "cust-001",
    "customer": {
      "id": "cust-001",
      "firstName": "John",
      "lastName": "Doe",
      "email": "john.doe@example.com",
      "phone": "+1-555-123-4567",
      "createdAt": "2024-01-15T10:30:00Z"
    },
    "orderDate": "2024-03-15T14:30:00Z",
    "status": "delivered",
    "totalAmount": 142.97,
    "shippingAddress": "123 Main St, New York, NY 10001"
  },
  {
    "id": "ord-002",
    "customerId": "cust-002",
    "customer": {
      "id": "cust-002",
      "firstName": "Jane",
      "lastName": "Smith",
      "email": "jane.smith@example.com",
      "phone": "+1-555-987-6543",
      "createdAt": "2024-02-20T14:45:00Z"
    },
    "orderDate": "2024-03-20T09:15:00Z",
    "status": "processing",
    "totalAmount": 89.99,
    "shippingAddress": "456 Oak Ave, Los Angeles, CA 90001"
  },
  {
    "id": "ord-003",
    "customerId": "cust-001",
    "customer": {
      "id": "cust-001",
      "firstName": "John",
      "lastName": "Doe",
      "email": "john.doe@example.com",
      "phone": "+1-555-123-4567",
      "createdAt": "2024-01-15T10:30:00Z"
    },
    "orderDate": "2024-03-25T16:00:00Z",
    "status": "pending",
    "totalAmount": 25.98,
    "shippingAddress": "123 Main St, New York, NY 10001"
  }
];

// Helper to generate ID
const generateId = (): string => `order-${String(orders.length + 1).padStart(3, '0')}`;

/**
 * GET /orders
 * List all orders with pagination
 */
router.get('/', (req: Request, res: Response) => {
  const page = parseInt(req.query.page as string) || 1;
  const limit = parseInt(req.query.limit as string) || 10;
  const offset = (page - 1) * limit;

  const paginatedData = orders.slice(offset, offset + limit);

  res.json({
    data: paginatedData,
    total: orders.length,
    page,
    limit
  });
});

/**
 * POST /orders
 * Create a new order
 */
router.post('/', (req: Request, res: Response) => {
  const newOrder: Order = {
    id: generateId(),
    ...req.body,
    
  };

  orders.push(newOrder);
  res.status(201).json(newOrder);
});

/**
 * GET /orders/:id
 * Get a order by ID
 */
router.get('/:id', (req: Request, res: Response) => {
  const order = orders.find(item => item.id === req.params.id);

  if (!order) {
    return res.status(404).json({
      error: 'Not Found',
      message: `Order with id '${req.params.id}' not found`
    });
  }

  res.json(order);
});

/**
 * PUT /orders/:id
 * Update a order
 */
router.put('/:id', (req: Request, res: Response) => {
  const index = orders.findIndex(item => item.id === req.params.id);

  if (index === -1) {
    return res.status(404).json({
      error: 'Not Found',
      message: `Order with id '${req.params.id}' not found`
    });
  }

  const updatedOrder: Order = {
    ...orders[index],
    ...req.body,
    id: req.params.id // Ensure ID cannot be changed
  };

  orders[index] = updatedOrder;
  res.json(updatedOrder);
});

/**
 * DELETE /orders/:id
 * Delete a order
 */
router.delete('/:id', (req: Request, res: Response) => {
  const index = orders.findIndex(item => item.id === req.params.id);

  if (index === -1) {
    return res.status(404).json({
      error: 'Not Found',
      message: `Order with id '${req.params.id}' not found`
    });
  }

  orders.splice(index, 1);
  res.status(204).send();
});

export { router as ordersRouter };
