/**
 * Units Router
 * Generated by Express.js CRUD Generator
 */

import { Router, Request, Response } from 'express';
import { Unit } from '../types';

const router = Router();

// In-memory data store with example data
let units: Unit[] = [
  {
    "id": "unit-001",
    "unitNumber": "pcs",
    "description": "Pieces"
  },
  {
    "id": "unit-002",
    "unitNumber": "kg",
    "description": "Kilograms"
  },
  {
    "id": "unit-003",
    "unitNumber": "ltr",
    "description": "Liters"
  },
  {
    "id": "unit-004",
    "unitNumber": "box",
    "description": "Box"
  }
];

// Helper to generate ID
const generateId = (): string => `unit-${String(units.length + 1).padStart(3, '0')}`;

/**
 * GET /units
 * List all units with pagination
 */
router.get('/', (req: Request, res: Response) => {
  const page = parseInt(req.query.page as string) || 1;
  const limit = parseInt(req.query.limit as string) || 10;
  const offset = (page - 1) * limit;

  const paginatedData = units.slice(offset, offset + limit);

  res.json({
    data: paginatedData,
    total: units.length,
    page,
    limit
  });
});

/**
 * POST /units
 * Create a new unit
 */
router.post('/', (req: Request, res: Response) => {
  const newUnit: Unit = {
    id: generateId(),
    ...req.body,
    
  };

  units.push(newUnit);
  res.status(201).json(newUnit);
});

/**
 * GET /units/:id
 * Get a unit by ID
 */
router.get('/:id', (req: Request, res: Response) => {
  const unit = units.find(item => item.id === req.params.id);

  if (!unit) {
    return res.status(404).json({
      error: 'Not Found',
      message: `Unit with id '${req.params.id}' not found`
    });
  }

  res.json(unit);
});

/**
 * PUT /units/:id
 * Update a unit
 */
router.put('/:id', (req: Request, res: Response) => {
  const index = units.findIndex(item => item.id === req.params.id);

  if (index === -1) {
    return res.status(404).json({
      error: 'Not Found',
      message: `Unit with id '${req.params.id}' not found`
    });
  }

  const updatedUnit: Unit = {
    ...units[index],
    ...req.body,
    id: req.params.id // Ensure ID cannot be changed
  };

  units[index] = updatedUnit;
  res.json(updatedUnit);
});

/**
 * DELETE /units/:id
 * Delete a unit
 */
router.delete('/:id', (req: Request, res: Response) => {
  const index = units.findIndex(item => item.id === req.params.id);

  if (index === -1) {
    return res.status(404).json({
      error: 'Not Found',
      message: `Unit with id '${req.params.id}' not found`
    });
  }

  units.splice(index, 1);
  res.status(204).send();
});

export { router as unitsRouter };
