/**
 * Order Validation Schema
 * Generated by Express.js CRUD Generator
 */

import { z } from 'zod';

export const orderSchema = z.object({
  id: z.string().optional(),
  customerId: z.string().optional(),
  orderDate: z.string().datetime().optional(),
  status: z.string().optional(),
  totalAmount: z.number().optional(),
  shippingAddress: z.string().optional(),
});
